version: '3'
services:
    tomcatmanager:
      build:
        context: .
        args:
          servername: manager
          conf: tomcat1/conf
          defaultWebApps: tomcat1/webapps
          lib: tomcat1/lib/*
      ports:
        - "8201:8080"
        - "9001:4567"
      environment:
        TZ: "Asia/Seoul"
    tomcatworker:
      build:
        context: .
        args:
          servername: worker
          conf: tomcat2/conf
          defaultWebApps: tomcat1/webapps
          lib: tomcat1/lib/*
      ports:
        - "8202:8080"
        - "9002:4567"
      environment:
        TZ: "Asia/Seoul"
    nginx:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      restart: always
      environment:
        TZ: "Asia/Seoul"
