version: '3'
services:
    tomcatmanager:
      build:
        context: .
        args:
          servername: manager
          conf: tomcat1/conf
          defaultWebApps: tomcat1/webapps
      ports:
        - "8201:8080"
    tomcatworker:
      build:
        context: .
        args:
          servername: worker
          conf: tomcat2/conf
          defaultWebApps: tomcat1/webapps
      ports:
        - "8202:8080"
    nginx:
        image: nginx
        ports:
            - "8200:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

        restart: always
